services:
  app:
    image: nguyenduc1603/fire_guard_be:v1.0.0
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_USER: postgres
      DB_PASSWORD: NguyenDuc@163
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NguyenDuc@163
      POSTGRES_DB: postgres
    ports:
      - '5432:5432' 
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
