version: '3.8'

services:
  app:
    container_name: fire_guard_app # Tên container ứng dụng
    image: nguyenduc1603/fire_guard_service:v1.0.1
    build:
      context: .
    ports:
      - "3000:3000" # Map port của ứng dụng ra ngoài
    environment:
      - DB_HOST=fire_guard_db # Hostname của database (trùng với container_name của PostgreSQL)
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=NguyenDuc@163
      - DB_NAME=fire_guard_db
      - NODE_ENV=production
    depends_on:
      - database # Đảm bảo database khởi động trước ứng dụng
    volumes:
      - ./public/uploads:/app/public/uploads

  database:
    container_name: fire_guard_db # Tên container database
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NguyenDuc@163
      POSTGRES_DB: fire_guard_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
